-- Table for 'favorites'
CREATE TABLE IF NOT EXISTS public.favorites
(
	-- auto-increment pk for unique favorite entries
	favorite_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	
	-- fk link to account table
	account_id integer NOT NULL,
	-- fk link to inventory table
	inv_id integer NOT NULL,

	-- auto add timestamp when favorite is created
	date_added timestamp DEFAULT CURRENT_TIMESTAMP,

	-- favorite_id as pk
	CONSTRAINT favorites_pkey PRIMARY KEY (favorite_id),

	-- Table relationships
	-- account table
	CONSTRAINT fk_account FOREIGN KEY (account_id)
		REFERENCES public.account (account_id)
		MATCH SIMPLE
		ON UPDATE CASCADE
		ON DELETE CASCADE, -- Related will be deleted
	-- inventory table
	CONSTRAINT fk_inventory FOREIGN KEY	(inv_id)
		REFERENCES public.inventory (inv_id)
		MATCH SIMPLE
		ON UPDATE CASCADE
		ON DELETE CASCADE -- Related will be deleted
);

-- Prevent duplicate favorites
ALTER TABLE public.favorites
	ADD CONSTRAINT unique_account_inventory
	UNIQUE (account_id, inv_id);